### ISSUE TITLE
README link to nirrt_star-icra24-evaluation.zip does not lead to this file

### ISSUE THREAD

**Issue by AlDanial** [tedhuang96/nirrt_star#2]
hi, looks like there's a typo at line 60 of ``README.md`` : 
<pre>
59 ### Evaluation for ICRA 2024
60 Download [nirrt_star-icra24-evaluation.zip](https://drive.google.com/file/d/1CZyPvj3K53vaXxOVTOpZCIU33zIg9dAS/view?usp=drive_link) and move the zip file into the root folder of this repo. Run
</pre>
The link shown doesn't lead to  ``nirrt_star-icra24-evaluation.zip``

**Comment by tedhuang96** [comment]
This is weird. This link works on my side no matter whether I was logged in or not. Can you provide a screenshot of the website when you click on this link?

**Comment by AlDanial** [comment]
Sure, here's what I see 
![zip_link](https://github.com/tedhuang96/nirrt_star/assets/1459933/beecaf6b-5da9-4c9f-a4ad-af7ce6a9602e)

**Comment by tedhuang96** [comment]
This is the `nirrt_star-icra24-evaluation.zip`. I zipped the folder `results/` inside `nirrt_star-icra24-evaluation.zip`. This folder `results/` includes the files used for evaluation analysis and visualization. You can click on folders to check out the structure of the directories.

**Comment by AlDanial** [comment]
I see.  Google Drive behaves differently for this ``.zip`` compared to the first two ``.zip`` files.  The earlier two prompted me directly for the download while this one appears in expanded form, which misled me.
