### ISSUE TITLE
environment problen

### ISSUE THREAD

**Issue by JaycgbEDC** [tedhuang96/nirrt_star#3]
Hi，there is a bug in setup part of ReadMe file.Exactly this command：pip install -e .
while there hasn't setup.py，so machine will throw an error

**Comment by tedhuang96** [comment]
Thank you for your question! Can you try skip the command `pip install -e .`, and run everything else in README?

I am pretty sure why I had this `pip install -e .` in README. Before organization of the code, There are files inside folders (not the root folder) that I need to run `python folder/file.py`, so I created a `setup.py` and run `pip install -e .` to avoid any import errors. 

Now after the code organization, every file we run python on is in the root folder, so I deleted `setup.py`, but I forgot to remove `pip install -e .`. Please let me know if there is any other question after you try skip the command `pip install -e .`, and run everything else in README.

**Comment by JaycgbEDC** [comment]
> Thank you for your question! Can you try skip the command `pip install -e .`, and run everything else in README?
> 
> I am pretty sure why I had this `pip install -e .` in README. Before organization of the code, There are files inside folders (not the root folder) that I need to run `python folder/file.py`, so I created a `setup.py` and run `pip install -e .` to avoid any import errors.
> 
> Now after the code organization, every file we run python on is in the root folder, so I deleted `setup.py`, but I forgot to remove `pip install -e .`. Please let me know if there is any other question after you try skip the command `pip install -e .`, and run everything else in README.

new problem: in the environment of python=3.9, open3d can't be installed.while python=3.8 can do that

**Comment by tedhuang96** [comment]
I tested on my linux machine and the installation works fine. If you are using different systems, it does not guarantee the packages can be successfully installed. You can go ahead with python 3.8 with open3d installed, and let me know if there are more questions.

**Comment by tedhuang96** [comment]
> Hi，there is a bug in setup part of ReadMe file.Exactly this command：pip install -e . while there hasn't setup.py，so machine will throw an error

`pip install -e .` is removed in setup instructions in README.md.  https://github.com/tedhuang96/nirrt_star/commit/285dd248b7e9c0c23e4b6362fcd6bdc8166457e7
