### ISSUE TITLE
About ‘def planning_block_gap’ and ‘def planning_random’

### ISSUE THREAD

**Issue by Maxianzhai** [tedhuang96/nirrt_star#4]
Hi Huang, I was reading``` nirrt_star_png_2d.py``` and ```nrrt_star_gng_2d.py``` and noticed that ```def planning_block_gap``` and ```def planning_random ``` do not seem to be used. After I comment out these two defs, the results don't seem to be affected by path planning in either environment. I would like to ask you what these two defs do.

**Comment by tedhuang96** [comment]
These functions are used here:

https://github.com/tedhuang96/nirrt_star/blob/69e81b3597d46b696b58ed483cad56296ce6c214/eval_planning_2d.py#L117-L125
